[package]
name = "rustemo"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
num_enum = "0.5"
rustemort = { path = "rustemort", version = "0.1"}

[dev-dependencies]
criterion = "0.3.5"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "docs-header.html" ]

[workspace]
members = ["rustemort"]
