# A workaround until CARGO_WORKSPACE_DIR is implemented
# See: https://github.com/rust-lang/cargo/issues/3946
# And: https://github.com/rust-lang/cargo/issues/3946#issuecomment-973132993

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
